[package]
name = "cirrus-volar-vole"
edition = "2024"
version.workspace = true
description.workspace = true

[dependencies]
cirrus-core = { version = "0.1.0", path = "../../cirrus-core" }
cirrus-recompile-core = { version = "0.1.0", path = "../../recompile/cirrus-recompile-core" }
volar-spec.workspace = true
hybrid-array.workspace = true
cipher.workspace = true
spin = { version = "0.10.1", default-features = false, features = ["mutex", "spin_mutex", "portable-atomic"] }

[target.'cfg(any(target_arch = "riscv32", target_arch = "arm"))'.dependencies]
portable-atomic = { version = "1", default-features = false, features = ["critical-section"] }

[dev-dependencies]
cirrus-recompile-rt = { version = "0.1.0", path = "../../recompile/cirrus-recompile-rt" }
cirrus-ert = { version = "0.1.0", path = "../../ert/cirrus-ert" }
rv-asm.workspace = true
cirrus-volar-boolar = { path = "../cirrus-volar-boolar" }
volar-ir = { version = "0.1.0", git = "https://github.com/portal-co/volar-ir.git" }
volar-ir-common = { version = "0.1.0", git = "https://github.com/portal-co/volar-ir.git" }
volar-lir-test-corpus = { version = "0.1.0", git = "https://github.com/portal-co/volar-ir.git" }
