//! The Rust source-generation recompile backend.
//!
//! [`generate_source`] renders a `cirrus_recompile_core::Program` as literal
//! Rust source: one `extern "C"` function that, given a pointer to the
//! target [`BackendTarget`] and a pointer to a `program.ops.len()`-element
//! scratch buffer, performs the recorded trace by calling a backend's pinned
//! functions in order -- the exact same functions the LLVM and assembly
//! backends call by name, for whichever backend (`cirrus-recompile-rt`'s own
//! `plaintext`, or one any other crate defines with its
//! `define_pinned_backend!`) the caller targets. [`CompiledProgram::compile`]
//! then does the "server precompiles once" half of the story for real: it
//! shells out to `rustc` to build that source into a loadable `cdylib`
//! linked against the already-built `cirrus-recompile-rt` rlib (plus
//! whichever `BackendTarget::extra_crates` a non-`cirrus-recompile-rt`
//! backend names), so the result is a genuine compiled artifact, not an
//! interpreter.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use cirrus_recompile_core::{
    LoopOp, LoopSlot, OptimizationOptions, PreparedProgram, PreparedStep, Program, ScheduledOp,
};

/// Which pinned-function backend module a compiled artifact targets.
///
/// `module_path` is the Rust path to that backend's pinned-function module
/// (e.g. `"cirrus_recompile_rt::plaintext"` or, for a backend a downstream
/// crate defines itself, `"cirrus_recompile_tests::gc_backend"`), which must
/// expose `Backend<..>`/`Wrapped<..>` type aliases and
/// `create`/`bitand`/`bitor`/`bitxor`/`mux` functions with the shape
/// `cirrus_recompile_rt::define_pinned_backend!` generates. `lifetimes`
/// names that backend's free lifetime parameters (e.g. `["'a", "'b"]` for a
/// garbler backend, `[]` for `plaintext`) -- every backend is generic *only*
/// over lifetimes (see `define_pinned_backend!`'s docs), so this is enough
/// to reconstruct its exact type at the call site.
pub struct BackendTarget {
    /// Rust path to the backend's pinned-function module.
    pub module_path: String,
    /// The backend's free lifetime parameters, without a leading `'`
    /// stripped -- e.g. `["'a", "'b"]`.
    pub lifetimes: Vec<String>,
    /// Extra crates (by Rust crate name, e.g. `"cirrus_recompile_tests"`)
    /// `module_path` needs `--extern`-linked, beyond `cirrus-recompile-rt`
    /// (always linked). A backend defined outside `cirrus-recompile-rt`
    /// itself -- see that crate's `define_pinned_backend!` docs -- names its
    /// own crate here.
    pub extra_crates: Vec<String>,
}

impl BackendTarget {
    /// The always-available native `bool` backend (`Context = ()`).
    pub fn plaintext() -> Self {
        Self {
            module_path: "cirrus_recompile_rt::plaintext".to_string(),
            lifetimes: Vec::new(),
            extra_crates: Vec::new(),
        }
    }

    fn generic_args(&self) -> String {
        if self.lifetimes.is_empty() {
            String::new()
        } else {
            format!("<{}>", self.lifetimes.join(", "))
        }
    }
}

/// Render `program` as literal Rust source defining `pub unsafe extern "C"
/// fn {fn_name}<..lifetimes..>(backend: *mut Backend<..>, buf: *mut
/// Wrapped<..>)` for `backend`'s target module.
///
/// Slots named in `program.inputs` are **not** initialized by the generated
/// function -- a caller populates them in the buffer before calling it, the
/// same convention `cirrus_recompile_rt::execute` and
/// `cirrus_recompile_core::interpret` use, so a value recorded at trace time
/// never shadows the value actually supplied at run time.
pub fn generate_source(program: &Program, fn_name: &str, backend: &BackendTarget) -> String {
    let prepared = program.prepare(&OptimizationOptions::default());
    generate_prepared_source(&prepared, fn_name, backend)
}

/// Render a prepared program as Rust source.
///
/// Table loops remain real counted loops in the generated artifact: varying
/// absolute slots are read from an iteration-major static table while
/// invariant slots stay immediates at the call site.
pub fn generate_prepared_source(
    program: &PreparedProgram,
    fn_name: &str,
    backend: &BackendTarget,
) -> String {
    let module = &backend.module_path;
    let generics = backend.generic_args();
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by cirrus-rust-codegen; do not edit by hand."
    );
    let _ = writeln!(out, "#[unsafe(no_mangle)]");
    let _ = writeln!(
        out,
        "pub unsafe extern \"C\" fn {fn_name}{generics}(backend: *mut {module}::Backend{generics}, buf: *mut {module}::Wrapped{generics}) {{"
    );
    let _ = writeln!(out, "    unsafe {{");
    for (loop_index, step) in program.steps.iter().enumerate() {
        match step {
            PreparedStep::Flat(ops) => {
                for &scheduled in ops {
                    if program.inputs.iter().any(|idx| *idx == scheduled.out) {
                        continue;
                    }
                    let _ = writeln!(out, "        {}", call_line(module, scheduled));
                }
            }
            PreparedStep::Loop(loop_step) => {
                let table = format!("cirrus_table_{loop_index}");
                let values = loop_step
                    .table
                    .iter()
                    .map(u32::to_string)
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(out, "        let {table}: &[u32] = &[{values}];");
                let _ = writeln!(
                    out,
                    "        for cirrus_iteration in 0..{}usize {{",
                    loop_step.iterations
                );
                let _ = writeln!(
                    out,
                    "            let cirrus_row = cirrus_iteration * {}usize;",
                    loop_step.fields_per_iteration
                );
                for &op in &loop_step.ops {
                    let _ = writeln!(out, "            {}", loop_call_line(module, op, &table));
                }
                let _ = writeln!(out, "        }}");
            }
        }
    }
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
    out
}

fn call_line(module: &str, scheduled: ScheduledOp) -> String {
    match scheduled.op {
        cirrus_recompile_core::Op::Create(value) => {
            format!(
                "{module}::create(backend, buf, {}, {});",
                value as u8, scheduled.out.0
            )
        }
        cirrus_recompile_core::Op::BitAnd(a, b) => {
            format!(
                "{module}::bitand(backend, buf, {}, {}, {});",
                a.0, b.0, scheduled.out.0
            )
        }
        cirrus_recompile_core::Op::BitOr(a, b) => {
            format!(
                "{module}::bitor(backend, buf, {}, {}, {});",
                a.0, b.0, scheduled.out.0
            )
        }
        cirrus_recompile_core::Op::BitXor(a, b) => {
            format!(
                "{module}::bitxor(backend, buf, {}, {}, {});",
                a.0, b.0, scheduled.out.0
            )
        }
        cirrus_recompile_core::Op::Mux { cond, then, r#else } => format!(
            "{module}::mux(backend, buf, {}, {}, {}, {});",
            cond.0, then.0, r#else.0, scheduled.out.0
        ),
    }
}

fn loop_slot(slot: LoopSlot, table: &str) -> String {
    match slot {
        LoopSlot::Static(slot) => slot.0.to_string(),
        LoopSlot::Table(field) => format!("{table}[cirrus_row + {field}usize]"),
    }
}

fn loop_call_line(module: &str, op: LoopOp, table: &str) -> String {
    match op {
        LoopOp::Create { val, out } => format!(
            "{module}::create(backend, buf, {}, {});",
            val as u8,
            loop_slot(out, table)
        ),
        LoopOp::BitAnd { a, b, out } => format!(
            "{module}::bitand(backend, buf, {}, {}, {});",
            loop_slot(a, table),
            loop_slot(b, table),
            loop_slot(out, table)
        ),
        LoopOp::BitOr { a, b, out } => format!(
            "{module}::bitor(backend, buf, {}, {}, {});",
            loop_slot(a, table),
            loop_slot(b, table),
            loop_slot(out, table)
        ),
        LoopOp::BitXor { a, b, out } => format!(
            "{module}::bitxor(backend, buf, {}, {}, {});",
            loop_slot(a, table),
            loop_slot(b, table),
            loop_slot(out, table)
        ),
        LoopOp::Mux {
            cond,
            then,
            r#else,
            out,
        } => format!(
            "{module}::mux(backend, buf, {}, {}, {}, {});",
            loop_slot(cond, table),
            loop_slot(then, table),
            loop_slot(r#else, table),
            loop_slot(out, table)
        ),
    }
}

/// This crate's own workspace `target` directory: `crates/recompile/
/// cirrus-rust-codegen` sits three levels below the workspace root.
fn workspace_target_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("cirrus-rust-codegen must live at crates/recompile/<name> under the workspace root")
        .join("target")
}

/// Find the most recently built rlib for the crate named `crate_name` (a
/// Rust crate name, e.g. `"cirrus_recompile_rt"`), so the generated source
/// can link against it directly instead of resolving symbols across a
/// separate dynamic library at load time.
fn find_rlib(crate_name: &str) -> PathBuf {
    let target = workspace_target_dir();
    let prefix = format!("lib{crate_name}");
    let mut best: Option<(std::time::SystemTime, PathBuf)> = None;
    for profile in ["debug", "release"] {
        let deps = target.join(profile).join("deps");
        let Ok(entries) = std::fs::read_dir(&deps) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let is_match = path
                .file_name()
                .and_then(|n| n.to_str())
                .is_some_and(|n| n.starts_with(&prefix) && n.ends_with(".rlib"));
            if !is_match {
                continue;
            }
            let modified = entry.metadata().and_then(|m| m.modified()).ok();
            if let Some(modified) = modified {
                if best.as_ref().is_none_or(|(t, _)| modified > *t) {
                    best = Some((modified, path));
                }
            }
        }
    }
    best.map(|(_, path)| path).unwrap_or_else(|| {
        panic!(
            "{crate_name} rlib not found under {} -- run `cargo build -p {crate_name}` first",
            target.display()
        )
    })
}

/// A [`Program`] compiled to a real, `rustc`-built, loaded artifact.
pub struct CompiledProgram {
    library: libloading::Library,
    fn_name: String,
}

impl CompiledProgram {
    /// Generate, compile with `rustc`, and load `program` (targeting
    /// `backend`) as a native artifact exposing `fn_name`.
    pub fn compile(program: &Program, fn_name: &str, backend: &BackendTarget) -> Self {
        Self::compile_with_options(program, fn_name, backend, &OptimizationOptions::default())
    }

    /// Compile `program` after preparing it with explicit optimization
    /// options.
    pub fn compile_with_options(
        program: &Program,
        fn_name: &str,
        backend: &BackendTarget,
        options: &OptimizationOptions,
    ) -> Self {
        let prepared = program.prepare(options);
        Self::compile_prepared(&prepared, fn_name, backend)
    }

    /// Compile an already prepared program.
    pub fn compile_prepared(
        program: &PreparedProgram,
        fn_name: &str,
        backend: &BackendTarget,
    ) -> Self {
        let source = generate_prepared_source(program, fn_name, backend);
        let dir = std::env::temp_dir().join(format!(
            "cirrus-rust-codegen-{}-{fn_name}",
            std::process::id()
        ));
        std::fs::create_dir_all(&dir)
            .expect("create scratch dir for generated Rust backend source");
        let src_path = dir.join(format!("{fn_name}.rs"));
        std::fs::write(&src_path, &source).expect("write generated Rust backend source");

        let rlib = find_rlib("cirrus_recompile_rt");
        let out_path = dir.join(format!(
            "{}{fn_name}.{}",
            std::env::consts::DLL_PREFIX,
            std::env::consts::DLL_EXTENSION
        ));

        let rustc = std::env::var("RUSTC").unwrap_or_else(|_| "rustc".into());
        let mut cmd = Command::new(rustc);
        cmd.arg("--edition")
            .arg("2024")
            .arg("--crate-type")
            .arg("cdylib")
            .arg("-O")
            // `cirrus-recompile-rt` (and any `extra_crates`) may themselves
            // depend on further rlibs (e.g. `cirrus-recompile-core`, or a
            // third-party crate a backend defined elsewhere needs); point
            // rustc at the shared `deps` directory so it can resolve those
            // transitive rlibs by name too.
            .arg("-L")
            .arg(rlib.parent().expect("rlib path has a parent directory"))
            .arg("--extern")
            .arg(format!("cirrus_recompile_rt={}", rlib.display()));
        for extra in &backend.extra_crates {
            let extra_rlib = find_rlib(extra);
            cmd.arg("--extern")
                .arg(format!("{extra}={}", extra_rlib.display()));
        }
        let status = cmd
            .arg(&src_path)
            .arg("-o")
            .arg(&out_path)
            .status()
            .expect("spawn rustc to compile the generated Rust backend source");
        assert!(
            status.success(),
            "rustc failed to compile the generated Rust backend source at {}",
            src_path.display()
        );

        // SAFETY: `out_path` is a cdylib this process just built from
        // `generate_source`'s output, whose only exported symbol is the
        // `extern "C" fn(*mut Backend, *mut Wrapped)` looked up in `run_raw`
        // below.
        let library = unsafe { libloading::Library::new(&out_path) }
            .expect("load the compiled Rust backend artifact");
        Self {
            library,
            fn_name: fn_name.to_string(),
        }
    }

    /// Run the compiled artifact against an arbitrary backend instance and
    /// scratch buffer.
    ///
    /// # Safety
    ///
    /// `Backend`/`Wrapped` must be exactly the types `compile`'s
    /// [`BackendTarget`] names (see its docs); `backend` must be valid for
    /// whatever mutable access that backend's pinned functions need, and
    /// `buf` must have at least as many `Wrapped` elements as the `Program`
    /// this artifact was compiled from has ops.
    pub unsafe fn run_raw<Backend, Wrapped>(&self, backend: *mut Backend, buf: *mut Wrapped) {
        // SAFETY: forwarded to the caller's own safety obligations above;
        // `fn_name` names the single such function `compile` built.
        unsafe {
            let symbol: libloading::Symbol<unsafe extern "C" fn(*mut Backend, *mut Wrapped)> = self
                .library
                .get(self.fn_name.as_bytes())
                .expect("resolve the generated backend's exported symbol");
            symbol(backend, buf);
        }
    }

    /// Run the compiled artifact against `inputs`, in `program.inputs`
    /// order, and read back `program.outputs`. Only valid for an artifact
    /// compiled with [`BackendTarget::plaintext`].
    pub fn run_plaintext(&self, program: &Program, inputs: &[bool]) -> Vec<bool> {
        assert_eq!(
            inputs.len(),
            program.inputs.len(),
            "input count must match the recorded program's input slots"
        );
        let mut buf = vec![false; program.ops.len()];
        for (&idx, &value) in program.inputs.iter().zip(inputs) {
            buf[idx.get()] = value;
        }
        // SAFETY: `()` and `bool` are exactly `BackendTarget::plaintext`'s
        // `Backend`/`Wrapped` types, and `buf` has `program.ops.len()`
        // elements.
        unsafe { self.run_raw(&mut () as *mut (), buf.as_mut_ptr()) };
        program.outputs.iter().map(|idx| buf[idx.get()]).collect()
    }

    /// Run an artifact compiled from `program` against the plaintext backend.
    pub fn run_prepared_plaintext(&self, program: &PreparedProgram, inputs: &[bool]) -> Vec<bool> {
        assert_eq!(
            inputs.len(),
            program.inputs.len(),
            "input count must match the recorded program's input slots"
        );
        let mut buf = vec![false; program.slots];
        for (&idx, &value) in program.inputs.iter().zip(inputs) {
            buf[idx.get()] = value;
        }
        // SAFETY: `()`/`bool` match the plaintext pinned backend and the
        // buffer has one element for each preserved raw slot.
        unsafe { self.run_raw(&mut () as *mut (), buf.as_mut_ptr()) };
        program.outputs.iter().map(|idx| buf[idx.get()]).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use cirrus_core::{ContextWithBitAnd, ContextWithBitOr, ContextWithBitXor, ContextWithCreate};
    use cirrus_recompile_core::Recorder;

    #[test]
    fn generated_source_skips_input_creates() {
        let mut recorder = Recorder::new();
        let a = recorder.create(true).unwrap();
        let and = ContextWithBitAnd::bitand(&mut recorder, a, a).unwrap();
        let program = recorder.finish(vec![a], vec![and]);

        let source = generate_source(&program, "run", &BackendTarget::plaintext());
        assert!(!source.contains("::create("));
        assert!(source.contains("cirrus_recompile_rt::plaintext::bitand(backend, buf, 0, 0, 1);"));
    }

    #[test]
    fn compiled_program_matches_the_reference_interpreter() {
        let mut recorder = Recorder::new();
        let a = recorder.create(false).unwrap();
        let b = recorder.create(false).unwrap();
        let and = ContextWithBitAnd::bitand(&mut recorder, a, b).unwrap();
        let or = ContextWithBitOr::bitor(&mut recorder, a, b).unwrap();
        let xor = ContextWithBitXor::bitxor(&mut recorder, a, b).unwrap();
        let mux = cirrus_core::ContextWithMux::mux(&mut recorder, a, or, xor).unwrap();
        let program = recorder.finish(vec![a, b], vec![and, or, xor, mux]);

        let compiled = CompiledProgram::compile(
            &program,
            "cirrus_rust_codegen_test_fn",
            &BackendTarget::plaintext(),
        );

        for &(x, y) in &[(false, false), (false, true), (true, false), (true, true)] {
            let expected = cirrus_recompile_rt::execute(&mut (), &program, &[x, y]);
            let actual = compiled.run_plaintext(&program, &[x, y]);
            assert_eq!(actual, expected, "mismatch for inputs ({x}, {y})");
        }
    }
}
