//! The Rust source-generation recompile backend.
//!
//! [`generate_source`] renders a `cirrus_recompile_core::Program` as literal
//! Rust source: one `extern "C"` function that, given a pointer to the
//! target [`BackendTarget`] and a pointer to a `program.ops.len()`-element
//! scratch buffer, performs the recorded trace by calling
//! `cirrus-recompile-rt`'s pinned functions in order -- the exact same
//! functions the LLVM and assembly backends call by name, for whichever
//! backend (`plaintext`, `gc`, `eval`, ...) the caller targets.
//! [`CompiledProgram::compile`] then does the "server precompiles once" half
//! of the story for real: it shells out to `rustc` to build that source into
//! a loadable `cdylib` linked against the already-built `cirrus-recompile-rt`
//! rlib, so the result is a genuine compiled artifact, not an interpreter.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use cirrus_recompile_core::{Op, Program};

/// Which `cirrus-recompile-rt` backend module a compiled artifact targets.
///
/// `module_path` is the Rust path to that backend's pinned-function module
/// (e.g. `"cirrus_recompile_rt::plaintext"` or
/// `"cirrus_recompile_rt::gc::backend"`), which must expose `Backend<..>`/
/// `Wrapped<..>` type aliases and `create`/`bitand`/`bitor`/`bitxor`/`mux`
/// functions with the shape `define_pinned_backend!` generates.
/// `lifetimes` names that backend's free lifetime parameters (e.g. `["'a",
/// "'b"]` for the `gc` backend, `[]` for `plaintext`) -- every backend is
/// generic *only* over lifetimes (see `define_pinned_backend!`'s docs), so
/// this is enough to reconstruct its exact type at the call site.
pub struct BackendTarget {
    /// Rust path to the backend's pinned-function module.
    pub module_path: String,
    /// The backend's free lifetime parameters, without a leading `'`
    /// stripped -- e.g. `["'a", "'b"]`.
    pub lifetimes: Vec<String>,
}

impl BackendTarget {
    /// The always-available native `bool` backend (`Context = ()`).
    pub fn plaintext() -> Self {
        Self {
            module_path: "cirrus_recompile_rt::plaintext".to_string(),
            lifetimes: Vec::new(),
        }
    }

    fn generic_args(&self) -> String {
        if self.lifetimes.is_empty() {
            String::new()
        } else {
            format!("<{}>", self.lifetimes.join(", "))
        }
    }
}

/// Render `program` as literal Rust source defining `pub unsafe extern "C"
/// fn {fn_name}<..lifetimes..>(backend: *mut Backend<..>, buf: *mut
/// Wrapped<..>)` for `backend`'s target module.
///
/// Slots named in `program.inputs` are **not** initialized by the generated
/// function -- a caller populates them in the buffer before calling it, the
/// same convention `cirrus_recompile_rt::execute` and
/// `cirrus_recompile_core::interpret` use, so a value recorded at trace time
/// never shadows the value actually supplied at run time.
pub fn generate_source(program: &Program, fn_name: &str, backend: &BackendTarget) -> String {
    let module = &backend.module_path;
    let generics = backend.generic_args();
    let mut out = String::new();
    let _ = writeln!(out, "// @generated by cirrus-rust-codegen; do not edit by hand.");
    let _ = writeln!(out, "#[unsafe(no_mangle)]");
    let _ = writeln!(
        out,
        "pub unsafe extern \"C\" fn {fn_name}{generics}(backend: *mut {module}::Backend{generics}, buf: *mut {module}::Wrapped{generics}) {{"
    );
    let _ = writeln!(out, "    unsafe {{");
    for (i, op) in program.ops.iter().enumerate() {
        if program.inputs.iter().any(|idx| idx.get() == i) {
            continue;
        }
        let line = match *op {
            Op::Create(v) => format!("{module}::create(backend, buf, {}, {i});", v as u8),
            Op::BitAnd(a, b) => format!("{module}::bitand(backend, buf, {}, {}, {i});", a.0, b.0),
            Op::BitOr(a, b) => format!("{module}::bitor(backend, buf, {}, {}, {i});", a.0, b.0),
            Op::BitXor(a, b) => format!("{module}::bitxor(backend, buf, {}, {}, {i});", a.0, b.0),
            Op::Mux { cond, then, r#else } => {
                format!("{module}::mux(backend, buf, {}, {}, {}, {i});", cond.0, then.0, r#else.0)
            }
        };
        let _ = writeln!(out, "        {line}");
    }
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
    out
}

/// This crate's own workspace `target` directory: `crates/recompile/
/// cirrus-rust-codegen` sits three levels below the workspace root.
fn workspace_target_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("cirrus-rust-codegen must live at crates/recompile/<name> under the workspace root")
        .join("target")
}

/// Find the most recently built `cirrus-recompile-rt` rlib, so the generated
/// source can link against it directly instead of resolving symbols across a
/// separate dynamic library at load time.
fn find_recompile_rt_rlib() -> PathBuf {
    let target = workspace_target_dir();
    let mut best: Option<(std::time::SystemTime, PathBuf)> = None;
    for profile in ["debug", "release"] {
        let deps = target.join(profile).join("deps");
        let Ok(entries) = std::fs::read_dir(&deps) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let is_match = path
                .file_name()
                .and_then(|n| n.to_str())
                .is_some_and(|n| n.starts_with("libcirrus_recompile_rt") && n.ends_with(".rlib"));
            if !is_match {
                continue;
            }
            let modified = entry.metadata().and_then(|m| m.modified()).ok();
            if let Some(modified) = modified {
                if best.as_ref().is_none_or(|(t, _)| modified > *t) {
                    best = Some((modified, path));
                }
            }
        }
    }
    best.map(|(_, path)| path).unwrap_or_else(|| {
        panic!(
            "cirrus-recompile-rt rlib not found under {} -- run `cargo build -p cirrus-recompile-rt [--features gc]` first",
            target.display()
        )
    })
}

/// A [`Program`] compiled to a real, `rustc`-built, loaded artifact.
pub struct CompiledProgram {
    library: libloading::Library,
    fn_name: String,
}

impl CompiledProgram {
    /// Generate, compile with `rustc`, and load `program` (targeting
    /// `backend`) as a native artifact exposing `fn_name`.
    pub fn compile(program: &Program, fn_name: &str, backend: &BackendTarget) -> Self {
        let source = generate_source(program, fn_name, backend);
        let dir = std::env::temp_dir().join(format!(
            "cirrus-rust-codegen-{}-{fn_name}",
            std::process::id()
        ));
        std::fs::create_dir_all(&dir).expect("create scratch dir for generated Rust backend source");
        let src_path = dir.join(format!("{fn_name}.rs"));
        std::fs::write(&src_path, &source).expect("write generated Rust backend source");

        let rlib = find_recompile_rt_rlib();
        let out_path = dir.join(format!(
            "{}{fn_name}.{}",
            std::env::consts::DLL_PREFIX,
            std::env::consts::DLL_EXTENSION
        ));

        let rustc = std::env::var("RUSTC").unwrap_or_else(|_| "rustc".into());
        let status = Command::new(rustc)
            .arg("--edition")
            .arg("2024")
            .arg("--crate-type")
            .arg("cdylib")
            .arg("-O")
            // `cirrus-recompile-rt` itself depends on `cirrus-recompile-core`
            // (and, for gc/eval targets, `cirrus-garbled-circuit`/`digest`/
            // `sha2`); point rustc at the same `deps` directory so it can
            // resolve those transitive rlibs by name.
            .arg("-L")
            .arg(rlib.parent().expect("rlib path has a parent directory"))
            .arg("--extern")
            .arg(format!("cirrus_recompile_rt={}", rlib.display()))
            .arg(&src_path)
            .arg("-o")
            .arg(&out_path)
            .status()
            .expect("spawn rustc to compile the generated Rust backend source");
        assert!(
            status.success(),
            "rustc failed to compile the generated Rust backend source at {}",
            src_path.display()
        );

        // SAFETY: `out_path` is a cdylib this process just built from
        // `generate_source`'s output, whose only exported symbol is the
        // `extern "C" fn(*mut Backend, *mut Wrapped)` looked up in `run_raw`
        // below.
        let library = unsafe { libloading::Library::new(&out_path) }
            .expect("load the compiled Rust backend artifact");
        Self {
            library,
            fn_name: fn_name.to_string(),
        }
    }

    /// Run the compiled artifact against an arbitrary backend instance and
    /// scratch buffer.
    ///
    /// # Safety
    ///
    /// `Backend`/`Wrapped` must be exactly the types `compile`'s
    /// [`BackendTarget`] names (see its docs); `backend` must be valid for
    /// whatever mutable access that backend's pinned functions need, and
    /// `buf` must have at least as many `Wrapped` elements as the `Program`
    /// this artifact was compiled from has ops.
    pub unsafe fn run_raw<Backend, Wrapped>(&self, backend: *mut Backend, buf: *mut Wrapped) {
        // SAFETY: forwarded to the caller's own safety obligations above;
        // `fn_name` names the single such function `compile` built.
        unsafe {
            let symbol: libloading::Symbol<unsafe extern "C" fn(*mut Backend, *mut Wrapped)> = self
                .library
                .get(self.fn_name.as_bytes())
                .expect("resolve the generated backend's exported symbol");
            symbol(backend, buf);
        }
    }

    /// Run the compiled artifact against `inputs`, in `program.inputs`
    /// order, and read back `program.outputs`. Only valid for an artifact
    /// compiled with [`BackendTarget::plaintext`].
    pub fn run_plaintext(&self, program: &Program, inputs: &[bool]) -> Vec<bool> {
        assert_eq!(
            inputs.len(),
            program.inputs.len(),
            "input count must match the recorded program's input slots"
        );
        let mut buf = vec![false; program.ops.len()];
        for (&idx, &value) in program.inputs.iter().zip(inputs) {
            buf[idx.get()] = value;
        }
        // SAFETY: `()` and `bool` are exactly `BackendTarget::plaintext`'s
        // `Backend`/`Wrapped` types, and `buf` has `program.ops.len()`
        // elements.
        unsafe { self.run_raw(&mut () as *mut (), buf.as_mut_ptr()) };
        program.outputs.iter().map(|idx| buf[idx.get()]).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use cirrus_core::{ContextWithBitAnd, ContextWithBitOr, ContextWithBitXor, ContextWithCreate};
    use cirrus_recompile_core::Recorder;

    #[test]
    fn generated_source_skips_input_creates() {
        let mut recorder = Recorder::new();
        let a = recorder.create(true).unwrap();
        let and = ContextWithBitAnd::bitand(&mut recorder, a, a).unwrap();
        let program = recorder.finish(vec![a], vec![and]);

        let source = generate_source(&program, "run", &BackendTarget::plaintext());
        assert!(!source.contains("::create("));
        assert!(source.contains("cirrus_recompile_rt::plaintext::bitand(backend, buf, 0, 0, 1);"));
    }

    #[test]
    fn compiled_program_matches_the_reference_interpreter() {
        let mut recorder = Recorder::new();
        let a = recorder.create(false).unwrap();
        let b = recorder.create(false).unwrap();
        let and = ContextWithBitAnd::bitand(&mut recorder, a, b).unwrap();
        let or = ContextWithBitOr::bitor(&mut recorder, a, b).unwrap();
        let xor = ContextWithBitXor::bitxor(&mut recorder, a, b).unwrap();
        let mux = cirrus_core::ContextWithMux::mux(&mut recorder, a, or, xor).unwrap();
        let program = recorder.finish(vec![a, b], vec![and, or, xor, mux]);

        let compiled = CompiledProgram::compile(&program, "cirrus_rust_codegen_test_fn", &BackendTarget::plaintext());

        for &(x, y) in &[(false, false), (false, true), (true, false), (true, true)] {
            let expected = cirrus_recompile_rt::execute(&mut (), &program, &[x, y]);
            let actual = compiled.run_plaintext(&program, &[x, y]);
            assert_eq!(actual, expected, "mismatch for inputs ({x}, {y})");
        }
    }
}
