[package]
name = "cirrus-volar-garble"
edition = "2024"
version.workspace = true
description.workspace = true

[dependencies]
cirrus-core = { version = "0.1.0", path = "../../cirrus-core" }
volar-spec.workspace = true
volar-oram.workspace = true
digest.workspace = true
hybrid-array.workspace = true
cipher.workspace = true

[dev-dependencies]
cirrus-recompile-core = { version = "0.1.0", path = "../../recompile/cirrus-recompile-core" }
cirrus-recompile-rt = { version = "0.1.0", path = "../../recompile/cirrus-recompile-rt" }
cirrus-ert = { version = "0.1.0", path = "../../ert/cirrus-ert" }
rv-asm.workspace = true
sha2 = { version = "0.11.0", default-features = false }
cirrus-volar-boolar = { path = "../cirrus-volar-boolar" }
cirrus-coroutine = { version = "0.1.0", path = "../../cirrus-coroutine" }
volar-ir = { version = "0.1.0", git = "https://github.com/portal-co/volar-ir.git" }
volar-lir-test-corpus = { version = "0.1.0", git = "https://github.com/portal-co/volar-ir.git" }
