[package]
name = "cirrus-armv8m-ert"
edition = "2024"
version.workspace = true
description = "Symbolic Armv8-M Thumb-2 interpreter facade"

[dependencies]
cirrus-core = { version = "0.1.0", path = "../../cirrus-core" }
cirrus-ert-core = { version = "0.1.0", path = "../cirrus-ert-core" }

[dev-dependencies]
cirrus-ert-sha256-fixture = { version = "0.1.0", path = "../cirrus-ert-sha256-fixture" }
