[package]
name = "cirrus-garbled-circuit"
edition = "2024"
version.workspace = true
description.workspace = true

[dependencies]
cirrus-core = { version = "0.1.0", path = "../../cirrus-core" }
digest = "0.11.3"

[dev-dependencies]
cirrus-armv8m-ert = { path = "../../ert/cirrus-armv8m-ert" }
cirrus-ert = { path = "../../ert/cirrus-ert" }
rv-asm.workspace = true
sha2 = { version = "0.11.0", default-features = false }
lazy-repo = { path = "../../../../lazy-repo/crates/lazy-repo", default-features = false }
